#!/bin/bash

# Load configuration
source ./rpi-arch-sdprep.conf && echo "[err] missing config file, this won't work..."

# Go to temp build directory
echo "[log] changing to temp directory ${temp_dir}"
temp_dir="$(mktemp --directory)" && cd "${temp_dir}"

# Check if all args are set
[[ ! -b "${device_name}" ]] && echo "[err] missing or incorrect device name" && exit 1
[[ ! -f "${file_image}" ]] && echo "[log] getting archlinux image" && wget "${image_url}"

# Umount any already mounted drives
for i in "${device_name}*"; do
    echo "[log] umounting "${i}" ..."
    umount "${i}"
done

# Partition the device
sfdisk "${device_name}" << EOF
label: dos
type=c, size=128M
type=83
EOF

# Create and mount filesystems
yes | mkfs.vfat "${device_name}1" && mkdir "boot" && mount "${device_name}1" "boot"
yes | mkfs.ext4 "${device_name}2" && mkdir "root" && mount "${device_name}2" "root"

# Unpack the image
bsdtar -xpf "${file_image}" -C root && sync
mv root/boot/* boot

# Set hostname
echo "${host_name}" > "root/etc/hostname"

#pacman -Syu sudo python git --needed --noconfirm

# Set sudoers file
echo "# Generated by installer script" > "root/etc/sudoers"
echo "root ALL=(ALL) ALL" >> "root/etc/sudoers"
echo "%sudo ALL=(ALL) ALL" >> "root/etc/sudoers"
echo "%wheel ALL=(ALL) ALL" >> "root/etc/sudoers"
echo "%ansible ALL=(ALL) ALL" >> "root/etc/sudoers"

# Create default user account
useradd --root "root/" \
        --create-home \
        --user-group \
        --system \
        --uid "${default_user_uid}" \
        --comment "${default_user_comment}" \
        "${default_user_name}"

# Exit
umount boot root
exit 0