#!/bin/bash

# Load configuration
source ./rpi-arch-sdprep.conf || echo "[err] missing config file, this won't work..."

# Get command line args that if added, will override the vars from config file
while [[ $# -gt 0 ]]; do
    case "${1}" in
        -d|--block-device) block_device_name="${2}"; shift ;;
        -p1|--part-1) block_device_part_1="${2}"; shift ;;
        -p2|--part-2) block_device_part_2="${2}"; shift ;;
        -h|--host-name) host_name="${2}"; shift ;;
    esac
done

# Check if all args are set
if [[ ! -b "${block_device_name}" ]]; then
    echo "[err] missing or incorrect device name"
    exit 1
fi

if [[ ! -f "${file_image_dir}/${file_image_name}" ]]; then
    if [[ ! -d  "${file_image_dir}" ]]; then
        echo "[log] creating archlinux image ${file_image_dir}"
        mkdir --parent "${file_image_dir}"
    fi
    echo "[log] getting archlinux image"
    wget --directory-prefix="${file_image_dir}" "${mirror_url}/${file_image_name}"
fi

# Umount any already mounted drives
for i in "${block_device_name}*"; do
    echo "[log] umounting "${i}" ..."
    umount "${i}"
done

# Partition the device
sfdisk "${block_device_name}" << EOF
label: dos
type=c, size=128M
type=83
EOF

# Go to temp build directory
temp_dir="$(mktemp --directory)"
echo "[log] changing to temp directory ${temp_dir}"
cd "${temp_dir}"

# Create and mount filesystems
yes | mkfs.vfat "${block_device_name}${block_device_part_1}" && mkdir "boot" && mount "${block_device_name}${block_device_part_1}" "boot"
yes | mkfs.ext4 "${block_device_name}${block_device_part_2}" && mkdir "root" && mount "${block_device_name}${block_device_part_2}" "root"

# Unpack the image
bsdtar -xpf "${file_image_dir}/${file_image_name}" -C root && sync
mv root/boot/* boot

# Set hostname
echo "${host_name}" > "root/etc/hostname"

# Set sudoers file
echo "# Generated by installer script" > "root/etc/sudoers"
echo "root ALL=(ALL) ALL" >> "root/etc/sudoers"
echo "%sudo ALL=(ALL) ALL" >> "root/etc/sudoers"
echo "%wheel ALL=(ALL) ALL" >> "root/etc/sudoers"
echo "%ansible ALL=(ALL) ALL" >> "root/etc/sudoers"

# Create default user account
#useradd --root "${temp_dir}/root/" \
#        --create-home \
#        --user-group \
#        --system \
#        --uid "${default_user_uid}" \
#        --comment "${default_user_comment}" \
#        "${default_user_name}"

# Exit
umount boot root
exit 0